name: StackEngineX
version: 1.0
main: me.phuc.stackenginex.StackEngineX
api-version: 1.21
author: Phuc
description: Stack system 128 for Paper

commands:
  stackenginex:
    description: Reload plugin config
    usage: /stackenginex
    permission: stackenginex.reload

permissions:
  stackenginex.reload:
    description: Allows reloading StackEngineX
    default: op
