name: StackEngineX
version: 1.0
main: me.phuc.stackenginex.StackEngine
api-version: 1.20
author: Pucwinmc
description: Item Stack Engine

commands:
  stackenginex:
    description: Reload plugin
    usage: /stackenginex reload
    permission: stackenginex.admin
    aliases: [sex]

permissions:
  stackenginex.admin:
    default: op
