name: StackEngineX
version: 1.0
main: me.phuc.stackenginex.StackEngineX
api-version: 1.21
author: Phuc

commands:
  stackenginex:
    description: Reload plugin
    permission: stackenginex.reload

permissions:
  stackenginex.reload:
    description: Cho phép reload plugin
    default: op
